// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGRFnZeXBV8oO_xlEFwMdrG0VTuDfShCQ',
    appId: '1:634437678748:web:14f4f237293e867e805f59',
    messagingSenderId: '634437678748',
    projectId: 'bingo-flutter-7494e',
    authDomain: 'bingo-flutter-7494e.firebaseapp.com',
    storageBucket: 'bingo-flutter-7494e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv98vFYoAcATqB2I3GC3Ed5FL-gLGUSCM',
    appId: '1:634437678748:android:c21fc2fe1a03f330805f59',
    messagingSenderId: '634437678748',
    projectId: 'bingo-flutter-7494e',
    storageBucket: 'bingo-flutter-7494e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3nGrvf0XKgee2bTRP5pqlx5n85A1psV4',
    appId: '1:634437678748:ios:b99165dc9a3df153805f59',
    messagingSenderId: '634437678748',
    projectId: 'bingo-flutter-7494e',
    storageBucket: 'bingo-flutter-7494e.appspot.com',
    iosClientId: '634437678748-vqnv85mmm8109mva88ua1bbb9uv0be7e.apps.googleusercontent.com',
    iosBundleId: 'com.syuancode.bingoFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3nGrvf0XKgee2bTRP5pqlx5n85A1psV4',
    appId: '1:634437678748:ios:b99165dc9a3df153805f59',
    messagingSenderId: '634437678748',
    projectId: 'bingo-flutter-7494e',
    storageBucket: 'bingo-flutter-7494e.appspot.com',
    iosClientId: '634437678748-vqnv85mmm8109mva88ua1bbb9uv0be7e.apps.googleusercontent.com',
    iosBundleId: 'com.syuancode.bingoFlutter',
  );
}
